modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="AutoMods"
description='''拔刀剑：重锋 的附属模组 —— 魂刀·两面宿傩。没有主模组时本模组不提供任何游戏内容。'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="slashblade"
mandatory=true
versionRange="[1.9,)"
ordering="AFTER"
side="BOTH"
